### PR TITLE
for cythonize SudachiPy

### PR DESCRIPTION
**Pull request by izziiyt**
Hi. I'm a developer of [SudachiPy](https://github.com/WorksApplications/SudachiPy), recently the number of users increased and this is depended by other softwares like [ginza](https://github.com/megagonlabs/ginza).

We are considering cythonize double array for performance, and I found this repository.

I modified your code and checked integration succeeded, but some changes has inconsistency with your original program. So I have questions.

Q1. Do you have idea to maintain this repository ? (Why I ask you this is because I can't see any change recently.)

Q2. If you say yes to Q1, could you help this PR ? I'd like to adopt this library if possible. 

Q3. If you say no to Q1, can I copy, paste and modify your code in SudachiPy ? (off course I'll write source. or transfer ownership of this repository is one option)

I'm waiting for your kindly answering ! Thanks.

### CODE REVIEW

**Comment by rixwew** [comment]
Thanks for your pr.
Sorry that I've not updated this repo these days.
Q1: I have plan to measure the performance of dictionary for different compiler options(like gcc -O3).
Q2, Q3: Both are welcome. After merge this pr, I'll bump up [dartsclone pip](https://pypi.org/project/dartsclone/) version.

**Comment by rixwew** [comment]
@izziiyt Looks great, I'll merge your pr after you remove WIP.

**Comment by izziiyt** [comment]
@rixwew Thanks for your help ! I wrote this code about 1 month ago. So I want to recheck by myself. After that I'll remove WIP. 

> Q1: I have plan to measure the performance of dictionary for different compiler options(like gcc -O3).

Great, but as a user, I want badge or much more unit tests at first :)

>Q2, Q3: Both are welcome. After merge this pr, I'll bump up dartsclone pip version.

If you have motivation to maintain this repository, I'd like to use your code as library.
When you think maintenance is difficult or loose motivation, it is welcome you to transfer ownership of this repository to WorksApplications and change your role to a maintainer. Thank you.

**Comment by rixwew** [comment]
> @rixwew Thanks for your help ! I wrote this code about 1 month ago. So I want to recheck by myself. After that I'll remove WIP.

thank you!

> When you think maintenance is difficult or loose motivation, it is welcome you to transfer ownership of this repository to WorksApplications and change your role to a maintainer. Thank you.

@izziiyt I added you and @kazuma-t to this repo's collaborators.
Feel free to change wrapper codes, or if you want to own, copy & paste to your code base:)

**Comment by izziiyt** [comment]
@rixwew Finally I found I don't have to change your code. Please merge a small modification to be used as library.

**Comment by rixwew** [comment]
thanks!

**Comment by izziiyt** [comment]
@rixwew Could you release library on PyPI ?

**Comment by rixwew** [comment]
@izziiyt Sorry for the late response. I updated PyPI package just now.

**Pull request merged**
