### PR TITLE
Build wheels and auto-deploy to test.pypi.org by using GitHub actions

### PR DESCRIPTION
**Pull request by hiroshi-matsuda-rit**
The build targets are linux-(amd64|i686), win-(x64|x86), and macos_x64 with python 3.[6-8].
The variations of macos x86 are dropped because the GitHub actions does not support this architecture, and also, Apple no longer supports 32 bit apps.

These build processes are triggered by pushing commits to any branches.
Please set TEST_PYPI_USER  and TEST_PYPI_PASSWORD on the Secret tab of your repository before accepting this PR.

Thanks,

### CODE REVIEW

**Comment by hiroshi-matsuda-rit** [comment]
@rixwew In addition, please make sure to bump up the version number in setup.py.
We used version=0.8.[1-5] to test auto-deploy functions, but maybe we should bump up the minor version for this kind of changes of installing procedure.

**Comment by rixwew** [comment]
Thank you @hiroshi-matsuda-rit
I tried `pip install -i https://test.pypi.org/simple/ dartsclone==0.8.5` , and the command failed when I have not installed cython.
Is it possible to install cython>=0.28 automatically when installing the dartsclone package?

**Comment by hiroshi-matsuda-rit** [comment]
@rixwew Oh, I did not see that error while installing local wheel archives.
I'd like to reproduce and revise the phenomenon.

**Comment by rixwew** [comment]
Thank you @hiroshi-matsuda-rit 
I tried it with Ubuntu 19.04 and Python 3.7.

**Comment by hiroshi-matsuda-rit** [comment]
@rixwew It seems that test.pypi.org might not serve correct cython packages. Actually, I have no idea how to specify the package dependent URLs.

**Comment by hiroshi-matsuda-rit** [comment]
This is the log when I installed cython>=0.28 from formal pypi before installing dartsclone of test.pypy.org.
```
$ python -m venv venv381
$ source venv381/bin/activate
(venv381) $ pip install cython>=0.28
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(venv381) $ pip install -i https://test.pypi.org/simple/ dartsclone==0.8.5
Looking in indexes: https://test.pypi.org/simple/
Collecting dartsclone==0.8.5
  Using cached https://test-files.pythonhosted.org/packages/d9/69/fdcf0d46eb71ce9d1ea7b55903b3f52886a12dda2201d9f69f7746e63b09/dartsclone-0.8.5-cp38-cp38-manylinux1_x86_64.whl
Requirement already satisfied: Cython in ./venv381/lib/python3.8/site-packages (from dartsclone==0.8.5) (0.29.15)
Installing collected packages: dartsclone
Successfully installed dartsclone-0.8.5
```

**Comment by hiroshi-matsuda-rit** [comment]
@rixwew Thank you, too! By the way, how about the version number issue? I suppose to bump up to '0.9.0' or '1.0.0'.

**Comment by rixwew** [comment]
After merging this PR, I want to change the github action trigger (like `on: push :tag :v*`) to avoid unexpected release to pypi.org, then I'll bump up to 0.9.0.
First of all, is it okay to merge this PR now? @hiroshi-matsuda-rit

**Comment by hiroshi-matsuda-rit** [comment]
@rixwew It sounds nice! Please merge this PR, now!

**Pull request merged**
